### ISSUE TITLE
Transcripts and Closing Commands

### ISSUE THREAD

**Issue by SirIncognito** [joshuad-media/infinity#20]
`-transcript` still works as a normal command and provides the transcript.

Instead `-close` will do a normal confirmation to close the ticket. Before deleting the channel, it will also provide the transcript.

Reason: this saves users having to do `-transcript` and `-close`

**Comment by joshuad-media** [comment]
Concept overview is to merge the command of transcript into the close command, however allowing the transcript command to remain available where needed.
